version: 2

models:
  - name: int_art_show__with_brand
    description: "Associe chaque exposition (art_show) à la marque (brand) qui l’a hébergée ou organisée."
    columns:
      - name: art_show_id
        tests: [not_null, unique]
      - name: art_show_title
      - name: brand_id
      - name: post_date
      - name: user_id

  - name: int_event__with_attendance
    description: "Ajoute le total de participations à chaque événement via agrégation de la table event_attendance."
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: event_type
      - name: event_name
      - name: event_date
      - name: total_attendance
      - name: list_attendees

  - name: int_interaction__with_user_and_type
    description: "Enrichit les interactions avec les métadonnées utilisateur et les types d'interactions."
    columns:
      - name: interaction_id
        tests: [not_null, unique]
      - name: interaction_type
      - name: user_id
      - name: user_type_id
      - name: published_at
      - name: linked_event_id
      - name: brand_id

  - name: int_session__with_event_unified
    description: "Associe chaque session à un événement ou une exposition selon la source de trafic (URL, interaction, etc.)."
    columns:
      - name: session_id
        tests: [not_null, unique]
      - name: user_id
      - name: brand_id
      - name: device_type
      - name: geo_ip
      - name: geo_name
      - name: started_at
      - name: ended_at
      - name: event_id
      - name: event_type

  - name: int_social_interaction__normalized
    description: "Unifie les interactions sociales provenant de plusieurs plateformes dans un format commun."
    columns:
      - name: interaction_id
        tests: [not_null, unique]
      - name: user_id
      - name: platform
      - name: action_type
      - name: timestamp
      - name: target_id
      - name: brand_id
      - name: session_id

  - name: int_qr_code__with_context
    description: "Fournit le contexte d'usage de chaque QR code : cible, marque, campagne, plateforme d'origine."
    columns:
      - name: qr_code_id
        tests: [not_null, unique]
      - name: target_type
      - name: target_id
      - name: brand_id
      - name: source_platform
      - name: campaign_code
      - name: label
