name: 'cda_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["models/cda_dbt/dbt_pipeline/seeds"]  # ✅ already correct
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cda_dbt:
    +schema: cda_pipeline
    +materialized: table

    dbt_pipeline:
      staging:
        +materialized: view
      intermediate:
        +materialized: view
      mart:
        +materialized: table

    _disabled:
      +enabled: false

    _hold_seeds_debug:
      +enabled: false

seed-paths: ["models/dbt_pipeline/seeds"]

seeds:
  cda_dbt:
    dbt_pipeline:
      +path: models/dbt_pipeline/seeds
      +quote_columns: false



