name: 'cda_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cda_dbt:
    +schema: cda_pipeline
    +materialized: table
    dbt_pipeline:
      staging:
        +materialized: view
      intermediate:
        +materialized: view
      mart:
        +materialized: table

seeds:
  cda_dbt:
    +schema: cda_pipeline
    +quote_columns: false