version: 2

sources:
  - name: wordpress
    database: cda-database
    schema: cda_owned
    tables:
      - name: users
      - name: posts
      - name: interactions
      - name: sessions
      - name: wp_users
      - name: brand

  - name: cda_api
    database: cda-database
    schema: cda_api
    tables:
      - name: payments

  - name: dbt_jdeajuriaguerra_cda_pipeline
    database: cda-database
    schema: cda_pipeline
    tables:
      - name: seed_art_show__brand_mapping
      - name: dim_event_type
      - name: dim_user_type
      - name: dim_brand_type
      - name: dim_art_show_type
      - name: dim_qr_code_type
      - name: dim_feedback_type
      - name: dim_interaction_type
