version: 2

sources:
  - name: wordpress
    database: cda-database
    schema: cda_owned
    tables:
      - name: wp_users
      - name: wp_posts
      - name: interaction
      - name: session
      - name: user
      - name: brand
      - name: event_attendance

  - name: cda_api
    database: cda-database
    schema: cda_api
    tables:
      - name: payments

  - name: dbt_jdeajuriaguerra_cda_pipeline
    database: cda-database
    schema: cda_pipeline
    tables:
      - name: dim_event_type
      - name: dim_user_type
      - name: dim_brand_type
      - name: dim_art_show_type
      - name: dim_qr_code_type
      - name: dim_feedback_type
      - name: dim_interaction_type

models:
  - name: stg_cda_owned__user
    description: "Staging model for real user data from cda_owned.user"
    columns:
      - name: user_id
        description: "Primary key for the user"
        tests:
          - not_null
          - unique
      - name: user_type_id
        description: "Foreign key to dim_user_type"
      - name: first_name
        description: "User first name"
      - name: last_name
        description: "User last name"
      - name: email
        description: "User email address"
      - name: created_at
        description: "Date of user registration"
      - name: updated_at
        description: "Date of last update"
