version: 2

sources:
  - name: cda_api
    database: cda-database
    schema: cda_api
    tables:
      - name: helloasso_payment
        description: "Full historical record of online payments processed via HelloAsso."
        columns:
          - name: payment_id
            description: "Unique identifier for the payment transaction."
          - name: amount
            description: "Amount paid in euros."
          - name: payment_status
            description: "Status of the payment (e.g. succeeded, failed)."
          - name: payer_json
            description: "Raw JSON object containing payer information."
          - name: payment_date
            description: "Timestamp of the payment event."
          - name: payer_email
            description: "Email address of the payer extracted from the JSON payload."
          - name: payer_first_name
            description: "First name of the payer extracted from the JSON payload."
          - name: payer_last_name
            description: "Last name of the payer extracted from the JSON payload."
          - name: payer_country
            description: "Country of the payer extracted from the JSON payload."
          - name: ingested_at
            description: "Ingestion timestamp of the record (generated during dbt run)."
      - name: payments
        description: "Raw HelloAsso payment data used as base input for stg_payments."

models:
  - name: stg_payments
    description: "Staging of HelloAsso payments enriched with parsed payer metadata."
    columns:
      - name: payment_id
        description: "Unique identifier for the payment transaction."
        tests: [not_null, unique]  # PRIMARY KEY

      - name: amount
        description: "Amount paid in euros."
        tests: [not_null]

      - name: payment_status
        description: "Status of the payment (e.g. succeeded, failed)."
        tests: [not_null]

      - name: raw_payer_json
        description: "Original JSON structure from HelloAsso containing payer metadata."
        tests: [not_null]

      - name: payment_date
        description: "Timestamp when the payment was processed."
        tests: [not_null]

      - name: payer_email
        description: "Email address of the payer."
        tests:
          - relationships:
              name: fk_payer_email_in_payments
              to: ref('stg_user')
              field: email

      - name: payer_first_name
        description: "First name of the payer."

      - name: payer_last_name
        description: "Last name of the payer."

      - name: payer_country
        description: "Country information of the payer."

      - name: ingested_at
        description: "Timestamp when the record was ingested into the data warehouse (calculated column)."
        tests: [not_null]
