version: 2

sources:
  - name: cda_api
    database: cda-database
    schema: cda_api
    tables:
      - name: payments
        description: "Raw HelloAsso payment data"
        columns:
          - name: id
            description: "Payment ID (renamed as payment_id in stg_ha__payments)"
            tests: [not_null, unique]
          - name: amount
            description: "Payment amount in cents."
          - name: state
            description: "Payment status."
          - name: payer
            description: "Raw payer JSON object."
          - name: date
            description: "Payment timestamp."

      - name: media
        description: "Raw Instagram media posts."

      - name: media_insights
        description: "Raw insights for Instagram media posts."

      - name: stories
        description: "Raw Instagram stories."

      - name: story_insights
        description: "Raw insights for Instagram stories."

      - name: user_insights
        description: "Daily Instagram user insights (reach, followers)."

      - name: user_lifetime_insights
        description: "Instagram user lifetime metrics."

      - name: users
        description: "Instagram user account metadata."

models:
  - name: stg_ha__payments
    description: "Staging model for HelloAsso payments, parsed and cleaned."
    columns:
      - name: payment_id
        description: "Unique payment identifier."
        tests: [not_null, unique]
      - name: amount
        description: "Payment amount in euros."
        tests: [not_null]
      - name: payment_status
        description: "Status of the payment (ex: accepted, canceled)."
        tests: [not_null]
      - name: payment_date
        description: "Parsed payment timestamp."
        tests: [not_null]
      - name: payer_email
        description: "Email address of the payer."
      - name: payer_first_name
        description: "First name of the payer."
      - name: payer_last_name
        description: "Last name of the payer."
      - name: payer_country
        description: "Country of the payer."
      - name: ingested_at
        description: "Timestamp when the record was ingested."
        tests: [not_null]
      - name: raw_payer_json
        description: "Original payer JSON blob."
        tests: [not_null]

  - name: stg_ig__media
    description: "Instagram media posts."
    columns:
      - name: id
        tests: [not_null, unique]
      - name: ig_id
      - name: caption
      - name: page_id
      - name: owner
      - name: owner_id
        description: "Foreign key to stg_ig__users.id"
        tests:
          - not_null
          - relationships:
              to: ref('stg_ig__users')
              field: id
      - name: children
      - name: first_child_id
      - name: username
      - name: media_url
      - name: permalink
      - name: shortcode
      - name: timestamp
        tests: [not_null]
      - name: like_count
      - name: media_type
      - name: thumbnail_url
      - name: comments_count
      - name: is_comment_enabled
      - name: media_product_type
      - name: business_account_id

  - name: stg_ig__media_insights
    description: "Metrics for each Instagram media post."
    columns:
      - name: id
        tests: [not_null, unique]
      - name: likes
      - name: reach
      - name: saved
      - name: shares
      - name: follows
      - name: page_id
      - name: comments
      - name: profile_visits
      - name: total_interactions
      - name: ig_reels_avg_watch_time
      - name: ig_reels_video_view_total_time
      - name: business_account_id

  - name: stg_ig__stories
    description: "Instagram stories."
    columns:
      - name: id
        tests: [not_null, unique]
      - name: ig_id
      - name: caption
      - name: page_id
      - name: owner_id
        description: "Foreign key to stg_ig__users.id"
        tests:
          - not_null
          - relationships:
              to: ref('stg_ig__users')
              field: id
      - name: username
      - name: media_url
      - name: permalink
      - name: shortcode
      - name: timestamp
        tests: [not_null]
      - name: like_count
      - name: media_type
      - name: thumbnail_url
      - name: media_product_type
      - name: business_account_id

  - name: stg_ig__story_insights
    description: "Instagram story metrics."
    columns:
      - name: id
        tests: [not_null, unique]
      - name: reach
      - name: shares
      - name: follows
      - name: page_id
      - name: replies
      - name: profile_visits
      - name: total_interactions
      - name: business_account_id

  - name: stg_ig__user_insights
    description: "Daily stats on reach and followers."
    columns:
      - name: date
        tests: [not_null]
      - name: reach
      - name: page_id
      - name: reach_week
      - name: reach_days_28
      - name: follower_count
      - name: online_followers_value
      - name: business_account_id

  - name: stg_ig__user_lifetime_insights
    description: "Account-level historical Instagram metrics."
    columns:
      - name: value
      - name: metric
      - name: page_id
      - name: breakdown
      - name: business_account_id

  - name: stg_ig__users
    description: "Instagram account metadata."
    columns:
      - name: id
        tests: [not_null, unique]
      - name: name
      - name: ig_id
      - name: page_id
      - name: website
      - name: username
      - name: biography
      - name: media_count
      - name: follows_count
      - name: followers_count
      - name: profile_picture_url
