version: 2

sources:
  - name: cda_api
    database: cda-database
    schema: cda_api
    tables:
      - name: payments
        description: "Raw HelloAsso payment data"
        columns:
          - name: id
            description: "Payment ID (rename as payment_id in stg_ha__payments)"
          - name: amount
          - name: payment_status
          - name: payer_json
          - name: payment_date
          - name: ingested_at

      - name: media
      - name: media_insights
      - name: stories
      - name: story_insights
      - name: user_insights
      - name: user_lifetime_insights
      - name: users

models:
  - name: stg_ha__payments
    description: "Staging model that renames raw HelloAsso payment fields and parses JSON"
    columns:
      - name: payment_id
        description: "Renamed from 'id'"
        tests: [not_null, unique]
      - name: amount
        tests: [not_null]
      - name: payment_status
        tests: [not_null]
      - name: raw_payer_json
        description: "Original HelloAsso JSON blob"
        tests: [not_null]
      - name: payment_date
        description: "Cleaned timestamp"
        tests: [not_null]
      - name: payer_email
        description: "Extracted email from JSON"
      - name: payer_first_name
      - name: payer_last_name
      - name: payer_country
      - name: ingested_at
        description: "Record ingestion timestamp"
        tests: [not_null]

  - name: stg_ig__media
    description: "Instagram media posts"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: ig_id
      - name: caption
      - name: page_id
      - name: owner
      - name: children
      - name: username
      - name: media_url
      - name: permalink
      - name: shortcode
      - name: timestamp
      - name: like_count
      - name: media_type
      - name: thumbnail_url
      - name: comments_count
      - name: is_comment_enabled
      - name: media_product_type
      - name: business_account_id

  - name: stg_ig__media_insights
    description: "Metrics for each Instagram media post"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: likes
      - name: reach
      - name: saved
      - name: shares
      - name: follows
      - name: page_id
      - name: comments
      - name: profile_visits
      - name: total_interactions
      - name: ig_reels_avg_watch_time
      - name: ig_reels_video_view_total_time
      - name: business_account_id

  - name: stg_ig__stories
    description: "Instagram stories"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: ig_id
      - name: caption
      - name: page_id
      - name: username
      - name: media_url
      - name: permalink
      - name: shortcode
      - name: timestamp
      - name: like_count
      - name: media_type
      - name: thumbnail_url
      - name: media_product_type
      - name: business_account_id

  - name: stg_ig__story_insights
    description: "Instagram story metrics"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: reach
      - name: shares
      - name: follows
      - name: page_id
      - name: replies
      - name: profile_visits
      - name: total_interactions
      - name: business_account_id

  - name: stg_ig__user_insights
    description: "Daily stats on reach and followers"
    columns:
      - name: date
        tests: [not_null]
      - name: reach
      - name: page_id
      - name: reach_week
      - name: reach_days_28
      - name: follower_count
      - name: online_followers_value
      - name: business_account_id

  - name: stg_ig__user_lifetime_insights
    description: "Account-level historical Instagram metrics"
    columns:
      - name: value
        description: "Raw JSON metric value"
      - name: metric
      - name: page_id
      - name: breakdown
      - name: business_account_id

  - name: stg_ig__users
    description: "Instagram account metadata"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: name
      - name: ig_id
      - name: page_id
      - name: website
      - name: username
      - name: biography
      - name: media_count
      - name: follows_count
      - name: followers_count
      - name: profile_picture_url

