version: 2

models:
  - name: int_qr_code__unified
    description: "Consolidated QR code content and display page mapping, combining all project streams and WordPress page details."
    columns:
      - name: source_id
        description: "ID of the QR code content sourced from project or project pages."
        tests:
          - not_null
          - unique

      - name: qr_code_id
        description: "ID used as the primary identifier for the QR code (duplicate of source_id)."
        tests:
          - not_null
          - unique

      - name: source_table
        description: "Name of the source table ('project', 'project_page2', etc.) from which the QR code content originates."
        tests:
          - not_null

      - name: content_slug
        description: "Slug (URL path segment) of the QR code content."
        tests:
          - not_null

      - name: content_title
        description: "Title of the QR code content."

      - name: brand_id_final
        description: "Final brand ID associated with the QR code content."

      - name: art_show_id_final
        description: "Final art show ID linked to the QR code content."

      - name: event_id_final
        description: "Final event ID connected to the QR code content."

      - name: artist_id
        description: "ID of the artist associated with the QR code content."

      - name: display_post_id
        description: "WordPress post ID of the page where the QR code display is published."

      - name: display_post_title
        description: "Title of the WordPress page linked to the QR code display."

      - name: display_post_slug
        description: "Slug (URL path segment) of the WordPress page displaying the QR code."

      - name: display_post_type
        description: "Post type of the WordPress page where the QR code is displayed (typically 'page')."

      - name: display_post_date
        description: "Publication date of the WordPress page displaying the QR code."
