version: 2

sources:
  - name: wordpress
    database: cda-database
    schema: cda_owned
    tables:
      - name: user
      - name: session
      - name: event
      - name: event_attendance
      - name: interaction
      - name: brand
      - name: art_show
      - name: transaction
      - name: wp_posts

models:
  - name: stg_cda_owned__user
  - name: stg_cda_owned__session
  - name: stg_cda_owned__event
  - name: stg_cda_owned__event_attendance
  - name: stg_cda_owned__interaction
  - name: stg_cda_owned__brand
  - name: stg_cda_owned__art_show
  - name: stg_cda_owned__transaction
