version: 2

sources:
  - name: cda_owned
    database: cda-database
    schema: cda_owned
    tables:
      - name: wp_posts
        description: "Table brute WordPress contenant tous les contenus : événements, marques, expositions, etc."

models:
  - name: stg__art_show
    description: "Modèle de staging des expositions d’art à partir des données WordPress."
    columns:
      - name: art_show_id
        tests: [not_null, unique]
      - name: art_show_title
      - name: art_show_slug
      - name: post_type
      - name: post_date

  - name: stg__brand
    description: "Modèle de staging des marques partenaires ou organisatrices (domaines, institutions, etc.)."
    columns:
      - name: brand_id
        tests: [not_null, unique]
      - name: brand_name
      - name: brand_slug
      - name: post_type
      - name: post_date
      - name: post_modified
      - name: post_parent
      - name: user_id

  - name: stg__event
    description: "Modèle de staging des événements ponctuels organisés pendant la manifestation."
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: event_name
      - name: event_type
      - name: event_start
      - name: event_end
      - name: updated_at

  - name: stg__event_attendance
    description: "Modèle de staging du suivi des présences lors des événements."
    columns:
      - name: event_attendance_id
        tests: [not_null, unique]
      - name: event_id
      - name: user_id
      - name: attended_at

  - name: stg__interaction
    description: "Modèle de staging des interactions numériques : QR, clics, réseaux sociaux."
    columns:
      - name: interaction_id
        tests: [not_null, unique]
      - name: interaction_type
      - name: source_platform
      - name: source_url
      - name: session_id
      - name: target_id
      - name: user_id
      - name: social_media_action
      - name: timestamp
      - name: details

  - name: stg__session
    description: "Modèle de staging des sessions utilisateur issues du site internet ou des QR codes."
    columns:
      - name: session_id
        tests: [not_null, unique]
      - name: source_platform
      - name: session_source_url
      - name: user_id
      - name: brand_id
      - name: device_type
      - name: geo_ip
      - name: geo_name
      - name: started_at
      - name: ended_at

  - name: stg__transaction
    description: "Modèle de staging des transactions hors HelloAsso (vente directe, CRM, etc.)."
    columns:
      - name: payment_id
        tests: [not_null, unique]
      - name: interaction_id
      - name: user_id
      - name: amount
      - name: status
      - name: created_at

  - name: stg__user
    description: "Modèle de staging des utilisateurs identifiés."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: user_type_id
      - name: first_name
      - name: last_name
      - name: email
      - name: country
      - name: created_at
      - name: updated_at

  - name: stg__wp_posts
    description: "Référence brute de tous les contenus WordPress pour audits croisés."
    columns:
      - name: user_id
      - name: user_login
      - name: user_email
      - name: user_registered