version: 2

sources:
  - name: cda_owned
    database: cda-database
    schema: cda_owned
    tables:
      - name: wp_posts
        description: "Raw WordPress table containing all types of content (events, brands, art shows, etc.)."
      - name: user
        description: "User table containing identified user records."
      - name: session
        description: "Session-level data for web tracking."
      - name: interaction
        description: "Interaction-level table for digital engagement."
      - name: event
        description: "Event metadata from the Costières program."
      - name: event_attendance
        description: "Attendance records for events."
      - name: wp_pages
        description: "Raw WordPress table with static page content."
      - name: project
        description: "Raw WordPress 'project' post type containing exhibition and artist entries."
      - name: project_page2
        description: "Raw WordPress 'project_page2' post type containing exhibition and artist entries."
      - name: project_page3
        description: "Raw WordPress 'project_page3' post type containing exhibition and artist entries."
      - name: project_page4
        description: "Raw WordPress 'project_page4' post type containing exhibition and artist entries."

models:
  - name: stg_wp__project
    description: "Staging model for WordPress `project` post type used for exhibitions, artists, and event content."
    columns:
      - name: project_id
        description: "Unique identifier for the project post."
        tests: [not_null, unique]
      - name: slug
        description: "URL-friendly slug of the post."
      - name: link
        description: "Full WordPress link to the post."
      - name: title
        description: "Rendered title of the project."
      - name: status
        description: "Post status (typically 'publish')."
      - name: type
        description: "Post type (should be 'project')."
      - name: author_id
        description: "ID of the user authoring the post."
        tests:
          - relationships:
              to: ref('stg_wp__user')
              field: id
              severity: warn
      - name: featured_media_id
        description: "ID of the associated media item (image or media)."
      - name: categories
        description: "List of WordPress category IDs linked to the post."
      - name: class_list
        description: "HTML class list assigned to the post."
      - name: content_rendered
        description: "Main body of the post in rendered HTML."
      - name: created_at
        description: "Formatted local creation timestamp."
        tests: [not_null]
      - name: modified_at
        description: "Formatted local last modification timestamp."
        tests: [not_null]
      - name: brand_id
        description: "Foreign key to brand entity if applicable."
      - name: artist_id
        description: "Foreign key to artist entity if applicable."
      - name: art_show_id
        description: "Foreign key to art show entity if applicable."
      - name: event_id
        description: "Foreign key to event entity if applicable."
      - name: _airbyte_meta
        description: "Airbyte metadata associated with the record."
      - name: _airbyte_generation_id
        description: "Airbyte internal generation tracking ID."

  - name: stg_wp__project_page2
    description: "Staging model for WordPress `project_page2` post type used for exhibitions, artists, and event content."
    columns:
      - name: project_id
        description: "Unique identifier for the project_page2 post."
        tests: [not_null, unique]
      - name: slug
        description: "URL-friendly slug of the post."
      - name: link
        description: "Full WordPress link to the post."
      - name: title
        description: "Rendered title of the project."
      - name: status
        description: "Post status (typically 'publish')."
      - name: type
        description: "Post type (should be 'project_page2')."
      - name: author_id
        description: "ID of the user authoring the post."
        tests:
          - relationships:
              to: ref('stg_wp__user')
              field: id
              severity: warn
      - name: featured_media_id
        description: "ID of the associated media item."
      - name: categories
        description: "List of category IDs linked to the post."
      - name: class_list
        description: "HTML class list assigned to the post."
      - name: content_rendered
        description: "Main body of the post in rendered HTML."
      - name: created_at
        description: "Formatted local creation timestamp."
        tests: [not_null]
      - name: created_at_gmt
        description: "Formatted GMT creation timestamp."
      - name: modified
        description: "Raw modification datetime."
        tests: [not_null]
      - name: template
        description: "WordPress template assigned to the post."
      - name: modified_gmt
        description: "Formatted GMT last modification timestamp."
      - name: brand_id
        description: "Foreign key to brand entity if applicable."
      - name: artist_id
        description: "Foreign key to artist entity if applicable."
      - name: art_show_id
        description: "Foreign key to art show entity if applicable."
      - name: event_id
        description: "Foreign key to event entity if applicable."
      - name: _airbyte_raw_id
        description: "Internal Airbyte record ID."
        tests: [not_null, unique]
      - name: _airbyte_extracted_at
        description: "Timestamp when Airbyte extracted this record."
        tests: [not_null]
      - name: _airbyte_meta
        description: "Airbyte metadata associated with the record."
      - name: _airbyte_generation_id
        description: "Airbyte internal generation tracking ID."

  - name: stg_wp__project_page3
    description: "Staging model for WordPress `project_page3` post type used for exhibitions, artists, and event content."
    columns:
      - name: project_id
        description: "Unique identifier for the project_page3 post."
        tests: [not_null, unique]
      - name: slug
        description: "URL-friendly slug of the post."
      - name: link
        description: "Full WordPress link to the post."
      - name: title
        description: "Rendered title of the project."
      - name: status
        description: "Post status (typically 'publish')."
      - name: type
        description: "Post type (should be 'project_page3')."
      - name: author_id
        description: "ID of the user authoring the post."
        tests:
          - relationships:
              to: ref('stg_wp__user')
              field: id
              severity: warn
      - name: featured_media_id
        description: "ID of the associated media item."
      - name: categories
        description: "List of category IDs linked to the post."
      - name: class_list
        description: "HTML class list assigned to the post."
      - name: content_rendered
        description: "Main body of the post in rendered HTML."
      - name: created_at
        description: "Formatted local creation timestamp."
        tests: [not_null]
      - name: created_at_gmt
        description: "Formatted GMT creation timestamp."
      - name: modified
        description: "Raw modification datetime."
        tests: [not_null]
      - name: template
        description: "WordPress template assigned to the post."
      - name: modified_gmt
        description: "Formatted GMT last modification timestamp."
      - name: brand_id
        description: "Foreign key to brand entity if applicable."
      - name: artist_id
        description: "Foreign key to artist entity if applicable."
      - name: art_show_id
        description: "Foreign key to art show entity if applicable."
      - name: event_id
        description: "Foreign key to event entity if applicable."
      - name: _airbyte_raw_id
        description: "Internal Airbyte record ID."
        tests: [not_null, unique]
      - name: _airbyte_extracted_at
        description: "Timestamp when Airbyte extracted this record."
        tests: [not_null]
      - name: _airbyte_meta
        description: "Airbyte metadata associated with the record."
      - name: _airbyte_generation_id
        description: "Airbyte internal generation tracking ID."

  - name: stg_wp__project_page4
    description: "Staging model for WordPress `project_page4` post type used for exhibitions, artists, and event content."
    columns:
      - name: project_id
        description: "Unique identifier for the project_page4 post."
        tests: [not_null, unique]
      - name: slug
        description: "URL-friendly slug of the post."
      - name: link
        description: "Full WordPress link to the post."
      - name: title
        description: "Rendered title of the project."
      - name: status
        description: "Post status (typically 'publish')."
      - name: type
        description: "Post type (should be 'project_page4')."
      - name: author_id
        description: "ID of the user authoring the post."
        tests:
          - relationships:
              to: ref('stg_wp__user')
              field: id
              severity: warn
      - name: featured_media_id
        description: "ID of the associated media item."
      - name: categories
        description: "List of category IDs linked to the post."
      - name: class_list
        description: "HTML class list assigned to the post."
      - name: content_rendered
        description: "Main body of the post in rendered HTML."
      - name: created_at
        description: "Formatted local creation timestamp."
        tests: [not_null]
      - name: created_at_gmt
        description: "Formatted GMT creation timestamp."
      - name: modified
        description: "Raw modification datetime."
        tests: [not_null]
      - name: template
        description: "WordPress template assigned to the post."
      - name: modified_gmt
        description: "Formatted GMT last modification timestamp."
      - name: brand_id
        description: "Foreign key to brand entity if applicable."
      - name: artist_id
        description: "Foreign key to artist entity if applicable."
      - name: art_show_id
        description: "Foreign key to art show entity if applicable."
      - name: event_id
        description: "Foreign key to event entity if applicable."
      - name: _airbyte_raw_id
        description: "Internal Airbyte record ID."
        tests: [not_null, unique]
      - name: _airbyte_extracted_at
        description: "Timestamp when Airbyte extracted this record."
        tests: [not_null]
      - name: _airbyte_meta
        description: "Airbyte metadata associated with the record."
      - name: _airbyte_generation_id
        description: "Airbyte internal generation tracking ID."
