version: 2

models:
  - name: int_dim__art_show_type
    description: "Dimension des types d’expositions : solo/group, indoor/outdoor, land art, etc."
    columns:
      - name: art_show_type_id
        tests: [not_null, unique]
      - name: art_show_type_label
      - name: art_show_type_description

  - name: int_dim__brand_type
    description: "Dimension des typologies de marques : hôte, sponsor, partenaire, institutionnel..."
    columns:
      - name: brand_type_id
        tests: [not_null, unique]
      - name: brand_type_label
      - name: brand_type_description

  - name: int_dim__event_type
    description: "Dimension des types d’événements : vernissage, VIP, rencontre artiste..."
    columns:
      - name: event_type_id
        tests: [not_null, unique]
      - name: event_type_label
      - name: event_type_description

  - name: int_dim__interaction_type
    description: "Dimension des types d’interactions (qr_code, owned_site, social_media)."
    columns:
      - name: interaction_type_id
        tests: [not_null, unique]
      - name: interaction_type_label
      - name: interaction_type_description

  - name: int_dim__payment_type
    description: "Source des paiements : HelloAsso, vente directe, institution, etc."
    columns:
      - name: payment_type_id
        tests: [not_null, unique]
      - name: payment_type_label
      - name: payment_type_description

  - name: int_dim__qr_code_type
    description: "Type de QR code : promotion, œuvre, exposition, artiste."
    columns:
      - name: qr_code_type_id
        tests: [not_null, unique]
      - name: qr_code_type_label
      - name: qr_code_type_description

  - name: int_dim__user_type
    description: "Typologie d’utilisateur : anonyme ou connecté (prospect/client/pro)."
    columns:
      - name: user_type_id
        tests: [not_null, unique]
      - name: user_type_label
      - name: user_type_description
