version: 2

models:
  - name: int_content__taxonomy
    description: "Unifie les métadonnées des contenus WordPress (posts, pages) pour usage analytique croisé."
    columns:
      - name: id
      - name: slug
      - name: title
      - name: type
      - name: published_at
      - name: source

  - name: int_session__with_event_unified
    description: "Prépare les sessions avec structure événementielle vide pour enrichissement progressif."
    columns:
      - name: session_id
        tests: [not_null, unique]
      - name: user_id
      - name: start_timestamp
      - name: end_timestamp
      - name: source_platform
      - name: session_source_url
      - name: device
      - name: geo_ip
      - name: geo_name
      - name: brand_id
      - name: event_id
      - name: event_type_id
      - name: art_show_id
      - name: art_show_type_id

  - name: int_session__with_interaction
    description: "Joint les sessions et les interactions (clics, QR, social) pour analyse comportementale enrichie."
    columns:
      - name: interaction_id
        tests: [not_null, unique]
      - name: session_id
      - name: user_id
      - name: interaction_type
      - name: interacted_at
      - name: url
      - name: device
      - name: geo_ip
      - name: geo_name
      - name: ingested_at

  - name: int_session__with_user_details
    description: "Ajoute les données utilisateurs consolidées aux sessions : infos personnelles, géo, etc."
    columns:
      - name: session_id
        tests: [not_null, unique]
      - name: session_source_url
      - name: started_at
      - name: ended_at
      - name: payer_first_name
      - name: payer_last_name
      - name: payer_email
      - name: payer_country
      - name: device
      - name: geo_ip
      - name: geo_name
      - name: user_ingested_at

  - name: int_user__consolidated
    description: "Fusionne les données utilisateurs de différentes sources (HelloAsso, autres) avec déduplication."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: payer_first_name
      - name: payer_last_name
      - name: payer_email
      - name: payer_country
      - name: device
      - name: geo_ip
      - name: geo_name
      - name: ingested_at

  - name: int_user__from_payments
    description: "Déduit les utilisateurs uniques des données de paiement HelloAsso (hash de l’email)."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: payer_first_name
      - name: payer_last_name
      - name: payer_email
      - name: payer_country
      - name: first_seen_date
      - name: ingested_at
    